name: llm-comparison

dependencies:
  - python >=3.8,<=3.9.7
  - antlr4-python3-runtime=4.8
  - pip
  - hydra-core=1.1.1
  - tokenizers
  - datasets=2.0.0
  - numpy=1.21.4
  - transformers=4.12.5
  - tqdm=4.62.3
  - pandas=1.3.4
  - setuptools <=59.5.0
  - pytorch=1.10.0
  - cudatoolkit=11.3