defaults:
  - _self_

p_model: bert
q_model: distilbert

dataset_loc: dataset_maker/datasets/miniboki-2022-04-01_22-58-30/miniboki
split: test
data_field: text
n_examples: none
batch_size: 1

kl_masking: none
size_average: none
reduce: none
reduction: mean
device: cpu

hydra:
  run: 
    dir: outputs/${p_model}-${q_model}/${now:%Y-%m-%d_%H-%M-%S.%f}
  sweep:
    dir: outputs
    subdir: /${p_model}-${q_model}/${now:%Y-%m-%d_%H-%M-%S.%f}
