defaults:
  - _self_

p_model: bert
q_model: distilbert

dataset_loc: dataset_maker/datasets/miniboki-2022-04-01_22-58-30/miniboki
split: test
data_field: text
n_examples: none
batch_size: 1

kl_masking: always
saved_indices: none
device: cpu

hydra:
  run: 
    dir: outputs/${masking:${kl_masking}}/${p_model}-${q_model}/${now:%Y-%m-%d_%H-%M-%S.%f}
  sweep:
    dir: outputs
    subdir: /${masking:${kl_masking}}/${p_model}-${q_model}/${now:%Y-%m-%d_%H-%M-%S.%f}
